routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->group(function(){

    // ---------- Gestion des pages de bases ---------- //

    Route::get('/books', 'BookController@index')
    ->name('books');

    Route::get('/auteurs', 'AuteurController@index')
    ->name('auteurs');

    Route::get('/auteur/{auteur}', 'AuteurController@show')
    ->name('auteur.show')->where('auteur', '[0-9]+');

    Route::get('/book/{book}', 'BookController@show')
    ->name('book.show')->where('book', '[0-9]+');


    // ---------- Gestion des auteurs ---------- //

    Route::get('/auteur/create', 'AuteurController@create')
    ->name('auteur.create');

    Route::post('/auteur/create', 'AuteurController@store')
    ->name('auteur.store');

    Route::delete('/auteur/{auteur}', 'AuteurController@destroy')
    ->name('auteur.destroy')->where('auteur', '[0-9]+');

    Route::get('/auteur/{auteur}/edit','AuteurController@edit')
    ->name('auteur.edit')->where('auteur', '[0-9]+');

    Route::put('/auteur/{auteur}/edit','AuteurController@update')
    ->name('auteur.update')->where('auteur', '[0-9]+');


    // ---------- Gestion des books ---------- //

    Route::get('/book/create', 'BookController@create')
    ->name('book.create');

    Route::post('/book/create', 'BookController@store')
    ->name('book.store');

    Route::delete('/book/{book}', 'BookController@destroy')
    ->name('book.destroy')->where('book', '[0-9]+');

    Route::get('/book/{book}/edit', 'BookController@edit')
    ->name('book.edit')->where('book', '[0-9]+');

    Route::put('/book/{book}/edit', 'BookController@update')
    ->name('book.update')->where('book', '[0-9]+');


    // ---------- Gestion des éditeurs ---------- //
    Route::resource('/editor', 'EditorController');


    // ---------- Gestion des catégories ---------- //
    Route::resource('/categorie', 'CategorieController');


    // ---------- Gestion des commentaires ---------- //
    Route::resource('/comment', 'CommentController')->except(['index', 'show', 'create']);


});


// ---------- Gestion des pages de bases ---------- //

Route::get('/', 'HomeController@index')
->name('home');

Route::get('/about', 'HomeController@about')
->name('about');

// ---------- Gestion des authentifications ---------- //
Auth::routes(['register' => true]);

resources/views/auteurs.blade.php
@extends('layouts/app')

@section('title')
    Books
@endsection

@section('content')

{{ Breadcrumbs::render('auteurs') }}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @can('create', 'App\Auteur')
                    <a class="btn btn-primary mb-4" href="{{ route('auteur.create') }}">Ajouter un éditeur</a>
                @endcan
                <div class="card">
                    <div class="card-header">Liste des auteurs : </div>
                        <div class="card-body">
                            <ul class="list-group-item">
                                @foreach ($auteurs as $auteur)
                                    @if ($auteur)
                                    <li class="list-group-item">
                                        <a href="{{ route('auteur.show', ['auteur'=>$auteur]) }}">{{ $auteur->prenom }} {{ $auteur->nom }}</a>
                                    </li>
                                     @endif
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books.blade.php
@extends('layouts/app')

@section('title')
    Books
@endsection

@section('content')

{{ Breadcrumbs::render('books') }}

<div class="container">
    @can('create', 'App\Book')
        <a class="btn btn-primary mb-4" href="{{ route('book.create') }}">Ajouter un livre</a>
    @endcan
    
    @foreach ($books as $book)
        <h2><a href="{{ route('book.show', ['book'=>$book]) }}">{{ $book->title }}</a></h2>
        @if ($book->auteur)
            <p>By <a href="{{ route('auteur.show', ['auteur'=>$book->auteur]) }}">{{ $book->auteur->prenom }} {{ $book->auteur->nom }}</a></p>
        @endif
        <p>{{ $book->summary }}</p>
    @endforeach
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

{{ Breadcrumbs::render('home') }}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    La librairie est un commerce de détail destiné à la vente de livres. 
                    Il existe différents types de points de vente du livre : librairies de livres neufs (généralistes ou spécialisées), 
                    librairies de livres anciens et d'occasion, maisons de la presse, librairies-papeteries, librairies ambulantes, 
                    grandes surfaces, librairies numériques.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@yield('title')</title>
        <link rel="stylesheet" href="{{ asset(mix('css/app.css')) }}">
    </head>

    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link" href="{{ route('home') }}">Home</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ route('about') }}">About</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ route('books') }}">Livres</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ route('auteurs') }}">Auteurs</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ route('editor.index') }}">Éditeurs</a></li>
                <li class="nav-item active"><a class="nav-link" href="{{ route('categorie.index') }}">Catégories</a></li>
            </ul>
        </nav>

        @yield('content')
     <script src="{{ asset(mix('js/app.js')) }}"></script>
     <script src="{{ asset(mix('js/manifest.js')) }}"></script>
     <script src="{{ asset(mix('js/vendor.js')) }}"></script>
    </body>

</html>