routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->group(function(){

    // ---------- Gestion des pages de bases ---------- //

    Route::get('/books', 'BookController@index')
    ->name('books');

    Route::get('/auteurs', 'AuteurController@index')
    ->name('auteurs');

    Route::get('/auteur/{auteur}', 'AuteurController@show')
    ->name('auteur.show')->where('auteur', '[0-9]+');

    Route::get('/book/{book}', 'BookController@show')
    ->name('book.show')->where('book', '[0-9]+');


    // ---------- Gestion des auteurs ---------- //

    Route::get('/auteur/create', 'AuteurController@create')
    ->name('auteur.create');

    Route::post('/auteur/create', 'AuteurController@store')
    ->name('auteur.store');

    Route::delete('/auteur/{auteur}', 'AuteurController@destroy')
    ->name('auteur.destroy')->where('auteur', '[0-9]+');

    Route::get('/auteur/{auteur}/edit','AuteurController@edit')
    ->name('auteur.edit')->where('auteur', '[0-9]+');

    Route::put('/auteur/{auteur}/edit','AuteurController@update')
    ->name('auteur.update')->where('auteur', '[0-9]+');


    // ---------- Gestion des books ---------- //

    Route::get('/book/create', 'BookController@create')
    ->name('book.create');

    Route::post('/book/create', 'BookController@store')
    ->name('book.store');

    Route::delete('/book/{book}', 'BookController@destroy')
    ->name('book.destroy')->where('book', '[0-9]+');

    Route::get('/book/{book}/edit', 'BookController@edit')
    ->name('book.edit')->where('book', '[0-9]+');

    Route::put('/book/{book}/edit', 'BookController@update')
    ->name('book.update')->where('book', '[0-9]+');


    // ---------- Gestion des éditeurs ---------- //
    Route::resource('/editor', 'EditorController');


    // ---------- Gestion des catégories ---------- //
    Route::resource('/categorie', 'CategorieController');


    // ---------- Gestion des commentaires ---------- //
    Route::resource('/comment', 'CommentController')->except(['index', 'show', 'create']);


});


// ---------- Gestion des pages de bases ---------- //

Route::get('/', 'HomeController@index')
->name('home');

Route::get('/about', 'HomeController@about')
->name('about');

// ---------- Gestion des authentifications ---------- //
Auth::routes(['register' => true]);

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
// use Illuminate\Support\Facades\App;

class Book extends Model
{
    protected $fillable = ['title', 'summary', 'auteur_id', 'editor_id'];

    function auteur(){
        return $this->belongsTo('App\Auteur');
    }

    function editor(){
        return $this->belongsTo('App\Editor');
    }

    function categories(){
        return $this->belongsToMany('App\Categorie');
    }

    function comments(){
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
use App\Http\Requests\BookRequest;

class BookController extends Controller
{

    function __construct()
    {
        $this->authorizeResource('App\Book');
    }

    function index(){
        $this->authorize('viewAny', \App\Book::class);
        $books = \App\Book::all();
        return view('books', ['books'=>$books]);
    }

    function show(\App\Book $book){
        return view('Book.show', ['book'=>$book]);
    }

    function create(){
        $auteurs = \App\Auteur::all();
        $editors = \App\Editor::all();
        $categories = \App\Categorie::all();
        return view('Book.create', ['auteurs'=>$auteurs, 'editors'=>$editors, 'categories'=>$categories]);
    }

    function store(\App\Http\Requests\BookRequest $request){
        $data = $request->validated();
        $book = new \App\Book();
        $book->fill($data);
        $book->save();
        if(isset($data['categorie'])){
            $book->categories()->sync($data['categorie']);
        }        
        return redirect()->route('book.show', ['book'=>$book]);
    }

    function edit(\App\Book $book){
        $auteurs = \App\Auteur::all();
        $editors = \App\Editor::all();
        $categories = \App\Categorie::all();
        return view('Book.edit', ['book'=>$book, 'auteurs'=>$auteurs, 'editors'=>$editors, 'categories'=>$categories]);
    }

    function update(\App\Book $book, \App\Http\Requests\BookRequest $request){
        $data = $request->validated();
        $book->fill($data);
        $book->save();
        $book->categories()->sync($data['categorie']);
        return redirect()->route('book.show', ['book'=>$book]);
    }

    function destroy(\App\Book $book){
        $book->delete();
        return redirect()->route('books');
    }
}

resources/views/Book/create.blade.php
@extends('layouts/app')

@section('title')
    Ajout d'un livre 
@endsection

@section('content')

{{ Breadcrumbs::render('book.create') }}

<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <h2 class="mb-4">Ajout d'un livre :</h1>
                <div class="row">

    

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <form action="{{ route('book.store') }}" method="POST">
        @csrf
        <input class="form-control" type="text" name="title" placeholder="Titre du livre" value="{{ old('title') }}">
        <input class="form-control mt-2" type="text" name="summary" placeholder="Résumé" value="{{ old('summary') }}">

        <label class="mt-4" for="">Séléctionner un éditeur :</label>
        <select class="form-control" name="editor_id">
            <option value="">Éditeurs</option>
            @foreach ($editors as $editor)
                <option value="{{ $editor->id }}"{{ $editor->id == old('editor_id') ? ' selected="selected"' : '' }}>{{ $editor->nom }}</option>
            @endforeach
        </select>
        
        <label for="">Séléctionner un auteur :</label>
        <select class="form-control" name="auteur_id">
            <option value="">Auteurs</option>
            @foreach ($auteurs as $auteur)
                <option value="{{ $auteur->id }}"{{ $auteur->id == old('auteur_id') ? ' selected="selected"' : '' }}>{{ $auteur->prenom }} {{ $auteur->nom }}</option>
            @endforeach
        </select>

        @foreach ($categories as $categorie)
            <input type="checkbox" name="categorie[]" value="{{ $categorie->id }} {{ array_search($categorie->id, old('categorie', [])) !== false ? ' checked="checked"' : '' }}">
            <label>{{ $categorie->nom }}</label>
        @endforeach

        <button class="btn btn-primary mt-2" type="submit">Valider</button>
    </form>

    </div>
</div>
</div>
</div>

@endsection

resources/views/Book/edit.blade.php
@extends('layouts/app')

@section('title')
Modification d'un livre
@endsection

@section('content')

{{ Breadcrumbs::render('book.edit', $book) }}

<h1>Modification d'un livre :</h1>

@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('book.update', ['book'=>$book]) }}" method="POST">
    @csrf
    @method('PUT')
    <input type="text" name="title" placeholder="Titre du livre" value="{{ old('title', $book->title) }}">
    <input type="text" name="summary" placeholder="Résumé" value="{{ old('summary', $book->summary) }}">

    <label for="">Séléctionner un éditeur :</label>
    <select name="editor_id">
        <option value="">Éditeurs</option>
        @foreach ($editors as $editor)
        <option value="{{ $editor->id }}"
            {{ $editor->id == old('editor_id', $book->editor_id) ? ' selected="selected"' : '' }}>{{ $editor->nom }}
        </option>
        @endforeach
    </select>


    <label for="">Séléctionner un auteur :</label>
    <select name="auteur_id">
        <option value="">Auteurs</option>
        @foreach ($auteurs as $auteur)
        <option value="{{ $auteur->id }}" {{ $auteur->id == old('auteur_id') ? ' selected="selected"' : '' }}>
            {{ $auteur->prenom }} {{ $auteur->nom }}</option>
        @endforeach
    </select>

    @php
    $categories_selected = $book->categories()->get()->pluck('id')->all();
    @endphp

    @foreach ($categories as $categorie)
    <input type="checkbox" name="categorie[]" value="{{ $categorie->id }}"
        {{ array_search($categorie->id, old('categorie', $categories_selected)) !== false ? ' checked="checked"' : '' }}">
    <label>{{ $categorie->nom }}</label>
    @endforeach

    <button type="submit">Valider</button>
</form>

@endsection

resources/views/Book/show.blade.php
@extends('layouts/app')

@section('title')
Auteur
@endsection

@section('content')

{{ Breadcrumbs::render('book', $book) }}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row">
                <div class=".col-sm">
                    @can('update', $book)
                    <a class="btn btn-primary mr-2" href="{{ route('book.edit', ['book'=>$book]) }}">Modifier le
                        livre</a>
                    @endcan
                </div>

                <div class=".col-sm">
                    @can('delete', $book)
                    <form action="{{ route('book.destroy', ['book'=>$book]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Supprimer le livre</button>
                    </form>
                    @endcan
                </div>
            </div>
            @if ($book->auteur)
            <h2 class="mt-4">Auteur : <a
                    href="{{ route('auteur.show', ['auteur'=>$book->auteur]) }}">{{ $book->auteur->prenom }}
                    {{ $book->auteur->nom }}</a></h2>
            @endif
            @if ($book->editor)
            <h2 class="mt-4">Éditeur : <a
                    href="{{ route('editor.show', ['editor'=>$book->editor]) }}">{{ $book->editor->nom }} </a></h2>
            @endif

            <div class="card mt-4">

                <div class="card-header">
                    <h1>{{ $book->title }}</h1>
                </div>
                <div class="card-body">
                    <h3>Résumé :</h3>
                    <p>{{ $book->summary }}</p>

                    @if ($book->categories()->get()->isNotEmpty())
                    <h3>Catégorie(s) : </h2>
                        @foreach ($book->categories as $categorie)
                        <li class="">
                            <a href="{{ route('categorie.show', ['categorie'=>$categorie]) }}">{{$categorie->nom}}</a>
                        </li>
                        @endforeach
                        @endif
                </div>
            </div>



            @can('create', \App\Comment::class)

            <h2 class="mt-4">Ajouter un commentaire : </h2>
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <form action="{{ route('comment.store') }}" method="POST">
                @csrf
                <input type="hidden" name="book_id" value="{{ $book->id }}">
                <textarea class="form-control" name="content" rows="5" cols="60"
                    placeholder="Nouveau commentaire">{{ old('content') }}</textarea>
                <button class="btn btn-primary mt-2" type="submit">Ajouter un commentaire</button>
            </form>
            @endcan

            @if ($book->comments()->get()->isNotEmpty())
            <h2 class="mt-3">Tous les commentaires :</h2>
            @foreach ($book->comments()->orderBy('created_at','desc')->get() as $comment)
            <div class="card container mb-2 mt-4">
                <p class="mt-3">{!! nl2br(e($comment->content), false) !!}</p>
                <p>{{ $comment->user->name }} - {{ $comment->created_at->format('m/d/Y H:i') }}</p>
            </div>

            <div class="row">
                <div class=".col-sm">
                    @can('update', $comment)
                    <a class="btn btn-sm btn-primary mr-2"
                        href="{{ route('comment.edit', ['comment'=>$comment]) }}">Modifier</a>
                    @endcan
                </div>

                <div class=".col-sm">
                    @can('delete', $comment)
                    <form action="{{ route('comment.destroy', ['comment'=>$comment]) }}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-sm btn-danger" type="submit">Supprimer</button>
                    </form>
                    @endcan
                </div>
            </div>





            @endforeach
            @endif

        </div>
    </div>



</div>
</div>



@endsection