routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->group(function(){

    // ---------- Gestion des pages de bases ---------- //

    Route::get('/books', 'BookController@index')
    ->name('books');

    Route::get('/auteurs', 'AuteurController@index')
    ->name('auteurs');

    Route::get('/auteur/{auteur}', 'AuteurController@show')
    ->name('auteur.show')->where('auteur', '[0-9]+');

    Route::get('/book/{book}', 'BookController@show')
    ->name('book.show')->where('book', '[0-9]+');


    // ---------- Gestion des auteurs ---------- //

    Route::get('/auteur/create', 'AuteurController@create')
    ->name('auteur.create');

    Route::post('/auteur/create', 'AuteurController@store')
    ->name('auteur.store');

    Route::delete('/auteur/{auteur}', 'AuteurController@destroy')
    ->name('auteur.destroy')->where('auteur', '[0-9]+');

    Route::get('/auteur/{auteur}/edit','AuteurController@edit')
    ->name('auteur.edit')->where('auteur', '[0-9]+');

    Route::put('/auteur/{auteur}/edit','AuteurController@update')
    ->name('auteur.update')->where('auteur', '[0-9]+');


    // ---------- Gestion des books ---------- //

    Route::get('/book/create', 'BookController@create')
    ->name('book.create');

    Route::post('/book/create', 'BookController@store')
    ->name('book.store');

    Route::delete('/book/{book}', 'BookController@destroy')
    ->name('book.destroy')->where('book', '[0-9]+');

    Route::get('/book/{book}/edit', 'BookController@edit')
    ->name('book.edit')->where('book', '[0-9]+');

    Route::put('/book/{book}/edit', 'BookController@update')
    ->name('book.update')->where('book', '[0-9]+');


    // ---------- Gestion des éditeurs ---------- //
    Route::resource('/editor', 'EditorController');


    // ---------- Gestion des catégories ---------- //
    Route::resource('/categorie', 'CategorieController');


    // ---------- Gestion des commentaires ---------- //
    Route::resource('/comment', 'CommentController')->except(['index', 'show', 'create']);


});


// ---------- Gestion des pages de bases ---------- //

Route::get('/', 'HomeController@index')
->name('home');

Route::get('/about', 'HomeController@about')
->name('about');

// ---------- Gestion des authentifications ---------- //
Auth::routes(['register' => true]);

app/Categorie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    protected $fillable = ['nom'];

    function books(){
        return $this->belongsToMany('App\Book');
    }
}

app/Http/Controllers/CategorieController.php
<?php

namespace App\Http\Controllers;

use App\Categorie;
use Illuminate\Http\Request;
use App\Http\Requests\CategorieRequest;

class CategorieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Categorie.index', ['categories'=>Categorie::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Categorie.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategorieRequest $request)
    {
        $data = $request->validated();
        $categorie = new \App\Categorie();
        $categorie->fill($data);
        $categorie->save();
        return redirect()->route('categorie.show', ['categorie'=>$categorie]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function show(Categorie $categorie)
    {
        return view('Categorie.show', ['categorie'=>$categorie]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function edit(Categorie $categorie)
    {
        return view('Categorie.edit', ['categorie'=>$categorie]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function update(CategorieRequest $request, Categorie $categorie)
    {
        $data = $request->validated();
        $categorie->fill($data);
        $categorie->save();
        return redirect()->route('categorie.show', ['categorie'=>$categorie]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Categorie  $categorie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categorie $categorie)
    {
        $categorie->delete();
        return redirect()->route('categorie.index');
    }
}

resources/views/Categorie/create.blade.php
@extends('layouts/app')

@section('title')
Ajout d'une catégorie
@endsection

@section('content')

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h2>Ajout d'une catégorie :</h2>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                <form action="{{ route('categorie.store') }}" method="POST">
                    @csrf
                    <input class="form-control" type="text" name="nom" placeholder="Nom de la catégorie"
                        value="{{ old('categorie') }}">

                    <button class="btn btn-primary mt-2" type="submit">Valider</button>
                </form>
            </div>
        </div>
    </div>
</div>







@endsection

resources/views/Categorie/edit.blade.php
@extends('layouts/app')

@section('title')
Modification d'une catégorie
@endsection

@section('content')

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h1>Modification d'une catégorie :</h1>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                <form action="{{ route('categorie.update', ['categorie'=>$categorie]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <input class="form-control" type="text" name="nom" placeholder="Nom de la catégorie"
                        value="{{ old('categorie', $categorie->nom) }}">
                    <button class="btn btn-primary mt-2" type="submit">Valider</button>
                </form>

            </div>
        </div>
    </div>
</div>

@endsection

resources/views/Categorie/index.blade.php
@extends('layouts/app')

@section('title')
    Catégories
@endsection

@section('content')

{{ Breadcrumbs::render('categories') }}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @can('create', 'App\Categorie')
                    <a class="btn btn-primary mb-4" id="new_categ" href="{{ route('categorie.create') }}">Ajouter une catégorie</a>
                @endcan
                <div class="card">
                    <div class="card-header">Liste des catégories :</div>
                        <div class="card-body">
                                <ul class="list-group-item">
                                    @foreach ($categories as $categorie) 
                                        @if ($categorie)
                                            <li class="list-group-item">  
                                                <a href="{{ route('categorie.show', ['categorie'=>$categorie]) }}">{{$categorie->nom}}</a>
                                            </li>   
                                        @endif
                                    @endforeach
                                </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
    
@endsection

resources/views/Categorie/show.blade.php
@extends('layouts/app')

@section('title')
Catégorie
@endsection

@section('content')

<div class="container">

    <div class="row">
        <div class=".col-sm mr-2 mb-4">
            @can('update', $categorie)
            <a class="btn btn-primary" href="{{ route('categorie.edit', ['categorie'=>$categorie]) }}">Modifier la
                catégorie</a>
            @endcan
        </div>

        <div class=".col-sm mr-2 mb-4">
            @can('delete', $categorie)
            <form action="{{ route('categorie.destroy', ['categorie'=>$categorie]) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Supprimer la catégorie</button>
            </form>
            @endcan
        </div>
    </div>



    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@if ($categorie)
                    <h1>{{ $categorie->nom }}</h1>
                    @endif </div>
                <div class="card-body">
                    <h2>Livres : </h2>

                    @if ($categorie->books()->get()->isNotEmpty())
                    <ul>
                        @foreach ($categorie->books as $book)
                        <li><a href="{{ route('book.show', ['book'=>$book]) }}">{{ $book->title }}</a></li>
                        @endforeach
                    </ul>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
</div>

@endsection