routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->group(function(){

    // ---------- Gestion des pages de bases ---------- //

    Route::get('/books', 'BookController@index')
    ->name('books');

    Route::get('/auteurs', 'AuteurController@index')
    ->name('auteurs');

    Route::get('/auteur/{auteur}', 'AuteurController@show')
    ->name('auteur.show')->where('auteur', '[0-9]+');

    Route::get('/book/{book}', 'BookController@show')
    ->name('book.show')->where('book', '[0-9]+');


    // ---------- Gestion des auteurs ---------- //

    Route::get('/auteur/create', 'AuteurController@create')
    ->name('auteur.create');

    Route::post('/auteur/create', 'AuteurController@store')
    ->name('auteur.store');

    Route::delete('/auteur/{auteur}', 'AuteurController@destroy')
    ->name('auteur.destroy')->where('auteur', '[0-9]+');

    Route::get('/auteur/{auteur}/edit','AuteurController@edit')
    ->name('auteur.edit')->where('auteur', '[0-9]+');

    Route::put('/auteur/{auteur}/edit','AuteurController@update')
    ->name('auteur.update')->where('auteur', '[0-9]+');


    // ---------- Gestion des books ---------- //

    Route::get('/book/create', 'BookController@create')
    ->name('book.create');

    Route::post('/book/create', 'BookController@store')
    ->name('book.store');

    Route::delete('/book/{book}', 'BookController@destroy')
    ->name('book.destroy')->where('book', '[0-9]+');

    Route::get('/book/{book}/edit', 'BookController@edit')
    ->name('book.edit')->where('book', '[0-9]+');

    Route::put('/book/{book}/edit', 'BookController@update')
    ->name('book.update')->where('book', '[0-9]+');


    // ---------- Gestion des éditeurs ---------- //
    Route::resource('/editor', 'EditorController');


    // ---------- Gestion des catégories ---------- //
    Route::resource('/categorie', 'CategorieController');


    // ---------- Gestion des commentaires ---------- //
    Route::resource('/comment', 'CommentController')->except(['index', 'show', 'create']);


});


// ---------- Gestion des pages de bases ---------- //

Route::get('/', 'HomeController@index')
->name('home');

Route::get('/about', 'HomeController@about')
->name('about');

// ---------- Gestion des authentifications ---------- //
Auth::routes(['register' => true]);

app/Editor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Editor extends Model
{
    use SoftDeletes;

    protected $fillable = ['nom'];

    function books(){
        return $this->hasMany('App\Book');
    }
}

app/Http/Controllers/EditorController.php
<?php

namespace App\Http\Controllers;

use App\Editor;
use Illuminate\Http\Request;
use App\Http\Requests\EditorRequest;


class EditorController extends Controller
{

    function __construct()
    {
        $this->authorizeResource('App\Editor');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Editor.index', ['editors'=>Editor::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Editor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EditorRequest $request)
    {
        $data = $request->validated();
        $editor = new \App\Editor();
        $editor->fill($data);
        $editor->save();
        return redirect()->route('editor.show', ['editor'=>$editor]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Editor  $editor
     * @return \Illuminate\Http\Response
     */
    public function show(Editor $editor)
    {
        return view('Editor.show', ['editor'=>$editor]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Editor  $editor
     * @return \Illuminate\Http\Response
     */
    public function edit(Editor $editor)
    {
        return view('Editor.edit', ['editor'=>$editor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Editor  $editor
     * @return \Illuminate\Http\Response
     */
    public function update(EditorRequest $request, Editor $editor)
    {
        $data = $request->validated();
        $editor->fill($data);
        $editor->save();
        return redirect()->route('editor.show', ['editor'=>$editor]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Editor  $editor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Editor $editor)
    {
        $editor->delete();
        return redirect()->route('editor.index');
    }
}

resources/views/Editor/create.blade.php
@extends('layouts/app')

@section('title')
Ajout d'un editeur
@endsection

@section('content')

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h1>Ajout d'un editeur :</h1>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                <form action="{{ route('editor.store') }}" method="POST">
                    @csrf
                    <input class="form-control" type="text" name="nom" placeholder="Nom de l'éditeur" value="{{ old('editor') }}">

                    <button class="btn btn-primary mt-2" type="submit">Valider</button>
                </form>

            </div>
        </div>
    </div>
</div>


@endsection

resources/views/Editor/edit.blade.php
@extends('layouts/app')

@section('title')
Modification d'un éditeur
@endsection

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h1>Modification d'un éditeur :</h1>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                <form action="{{ route('editor.update', ['editor'=>$editor]) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <input class="form-control" type="text" name="nom" placeholder="Nom de l'éditeur"
                        value="{{ old('editor', $editor->nom) }}">
                    <button class="btn btn-primary mt-2" type="submit">Valider</button>
                </form>

            </div>
        </div>
    </div>
</div>

@endsection

resources/views/Editor/index.blade.php
@extends('layouts/app')

@section('title')
    Editeurs
@endsection

@section('content')

{{ Breadcrumbs::render('editors') }}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @can('create', \App\Editor::class)
                    <a class="btn btn-primary mb-4" href="{{ route('editor.create') }}">Ajouter un éditeur</a>
                @endcan
                <div class="card">
                    <div class="card-header">Liste des éditeurs :</div>
                        <div class="card-body">
                            <ul class="list-group-item">
                                @foreach ($editors as $editor) 
                                    @if ($editor)
                                        <li class="list-group-item">  
                                            <a href="{{ route('editor.show', ['editor'=>$editor]) }}">{{$editor->nom}}</a> 
                                        </li>   
                                    @endif
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
@endsection

resources/views/Editor/show.blade.php
@extends('layouts/app')

@section('title')
    Editeur 
@endsection

@section('content')

{{ Breadcrumbs::render('editor', $editor) }}

     <div class="container">

          <div class="row">
               <div class=".col-sm mr-2 mb-4">
                    @can('update', $editor)
                         <a class="btn btn-primary" href="{{ route('editor.edit', ['editor'=>$editor]) }}">Modifier l'éditeur</a>
                    @endcan
               </div>

               <div class=".col-sm">
                    @can('delete', $editor)
                         <form action="{{ route('editor.destroy', ['editor'=>$editor]) }}" method="POST">
                              @csrf
                              @method('DELETE')
                              <button type="submit" class="btn btn-danger">Supprimer l'éditeur</button>
                         </form>
                    @endcan 
               </div>
          </div>

          
                 
          <div class="row justify-content-center">
              <div class="col-md-8">
                  <div class="card">
                      <div class="card-header">@if ($editor)
                                                  <h1>{{ $editor->nom }}</h1>
                                               @endif</div>
                          <div class="card-body">
                                   <h2>Livres : </h2>

                                   @if ($editor->books()->get()->isNotEmpty())
                                        <ul>
                                             @foreach ($editor->books as $book)
                                                  <li><a href="{{ route('book.show', ['book'=>$book]) }}">{{ $book->title }}</a></li>
                                             @endforeach
                                        </ul>
                                   @endif
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
@endsection